#!/usr/bin/perl

#
#   CIS*2250 Project: Team London
#   User Interface
#

use strict;

my ($setQ, $respond1, $respond2, $respond3, $respond4, $respond5) = 0;
my ($flag, $mainFlag, $exitFlag, $programFlag) = 0;

print "\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Welcome to Team London's program!  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
print "\nINSTRUCTIONS:\n >> Please enter the numbers corresponding to your choices.\n >> PRESS 9 TO EXIT.\n";

while ($programFlag == 0) {
	while ($mainFlag == 0) {
		
		print "\nQUESTION TYPES:"; 
		print "\nQuestion Set 1: What location had the highest/lowest rate of a specific violation in a specific year?";
		print "\nQuestion Set 2: What location had the highest/lowest percent change in a specific violation between two years?";
		print "\nQuestion Set 3: What was the safest/least safe place to do different things in Canada in a specific year?";
		
		print "\n\nWould you like to pick Quesiton Set 1, 2 or 3? ";
		$setQ = <STDIN>;
		chomp $setQ;

		if ($setQ == 9) {
			exit;
		}

		if ($setQ == 1 || $setQ == 2 || $setQ == 3) {
			$mainFlag = 1;
		}

		$flag = 0;
		
		if ($setQ == 1) {
			print "\nFILL IN THE BLANKS:\nWhat (province/city) had the (highest/lowest) rate of (violation) in (year)?\n";
			while ($flag == 0) {
				print "\nProvince or city? (1 for province, 2 for city): ";
				$respond1 = <STDIN>;
				chomp $respond1;
				if ( ($respond1 == 1 || $respond1 == 2) && $respond1 != '') {
					$flag = 1;
				}
			}

			$flag = 0;
			while ($flag == 0) { 
				print "\nHighest or Lowest (1 for highest, 2 for lowest): ";
				$respond2 = <STDIN>;
				chomp $respond2;
				if (($respond2 == 1 || $respond2 == 2) && $respond2 != '') {
					$flag = 1;
				}
			}

			$flag = 0;
			print "\n\n     ~~~~~~~~~~~~~~~~~~~ VIOLATION NUMBERS ~~~~~~~~~~~~~~~~~~~\n\n";
			print "     Abduction under the age 14, not parent or guardian     39\n";
			print "     Arson                                                  84\n";
			print "     Dangerous vehicle operation, causing death            161\n";
			print "     Luring a child                                         21\n";
			print "     Participate in activity of terrorist group            128\n";
			print "     Total breaking and entering                            65\n";
			print "     Total Criminal Code traffic violations                148\n";
			print "     Total Impaired Driving                                149\n";
			print "     Total robbery                                          34\n";
			print "     Total violent Criminal Code violations                  4\n";
			print "     Shoplifting \$5,000 or under                            79\n";
			print "     Total sexual violations against children               17\n";
				
			while ($flag == 0){
				print "\nViolation number: ";
				$respond3 = <STDIN>;
				chomp $respond3;
				if ($respond3 == 39 || $respond3 == 84 || $respond3 == 161 || $respond3 == 21 || $respond3 == 128 || $respond3 == 65 || $respond3 == 148 || $respond3 == 149 || $respond3 == 34 || $respond3 == 4 || $respond3 == 79 || $respond3 == 17) {
					$flag = 1;
				}
			}

			$flag = 0;
			while ($flag == 0) {
				print "Year (1998 - 2015): ";
				$respond4 = <STDIN>;
				chomp $respond4;
				if ($respond4 >= 1998 && $respond4 <= 2015) {
					$flag = 1;
				}
			}   
			$flag = 0;
				
			print "\nresponse 1 = $respond1\n";
			print "\nresponse 2 = $respond2\n";
			print "\nresponse 3 = $respond3\n";
			print "\nresponse 4 = $respond4\n";
		     
		} elsif ($setQ == 2) {
			print "\nFILL IN THE BLANKS:\nWhat (province/city) had the (highest/lowest) percent change in (violation) from (year) to (year)?\n";
			
			while ($flag == 0) {
				print "\nProvince or city? (1 for province, 2 for city): ";
				$respond1 = <STDIN>;
				chomp $respond1;
				if (($respond1 == 1 || $respond1 == 2) && $respond1 != '') {
					$flag = 1;
				}
			}
			$flag = 0;
			while ($flag == 0) {
				print "\nHighest or Lowest (1 for highest, 2 for lowest): ";
				$respond2 = <STDIN>;
				chomp $respond2;
				if (($respond2 == 1 || $respond2 == 2) && $respond2 != '') {
					$flag = 1;
				}
			}
			$flag = 0;
			print "\n\n     ~~~~~~~~~~~~~~~~~~~ VIOLATION NUMBERS ~~~~~~~~~~~~~~~~~~~\n\n";
			print "     Abduction under the age 14, not parent or guardian     39\n";
			print "     Arson                                                  84\n";
			print "     Dangerous vehicle operation, causing death            161\n";
			print "     Luring a child                                         21\n";
			print "     Participate in activity of terrorist group            128\n";
			print "     Total breaking and entering                            65\n";
			print "     Total Criminal Code traffic violations                148\n";
			print "     Total Impaired Driving                                149\n";
			print "     Total robbery                                          34\n";
			print "     Total violent Criminal Code violations                  4\n";
			print "     Shoplifting \$5,000 or under                            79\n";
			print "     Total sexual violations against children               17\n";
				
			while ($flag == 0){    
				print "\nViolation number: ";
            	$respond3 = <STDIN>;
            	chomp $respond3;
            	if ($respond3 == 39 || $respond3 == 84 || $respond3 == 161 || $respond3 == 21 || $respond3 == 128 || $respond3 == 65 || $respond3 == 148 || $respond3 == 149 || $respond3 == 34 || $respond3 == 4 || $respond3 == 79 || $respond3 == 17) {
                	$flag = 1;
            	}
        	}
        	#year
    	} elsif ($setQ == 3) {
			print "\nFILL IN THE BLANKS:\nWhat was the (safest/least safe) (province/city) to (desired action) in (year)?\n";
			while ($flag == 0) {
				print "\nSafest or least safe? (1 for safest, 2 for least safe): ";
				$respond1 = <STDIN>;
				chomp $respond1;
				if (($respond1 == 1 || $respond1 == 2) && $respond1 != '') {
					$flag = 1;
				}
			}

			$flag = 0;
			while ($flag == 0) {
				print "\nProvince or city? (1 for province, 2 for city): ";
				$respond2 = <STDIN>;
				chomp $respond2;
				if (($respond2 == 1 || $respond2 == 2) && $respond2 != '') {
					$flag = 1;
				}
			}
			
			print "\n\n     ~~~~~~ CRITERIA ~~~~~~\n\n";
			print "     Live 				1\n";
			print "		Raise a child       2\n";
			print "     Drive               3\n";
			print "     Start a Business    4\n";
			print "     Own a home          5\n";
			$flag = 0;
			while ($flag == 0) {
				$respond3 = <STDIN>;
				chomp $respond3;
				if ($respond3 != '' && ($respond3 == 1 || $respond3 == 2 || $respond3 == 3 || $respond3 == 4 || $respond3 == 0)) {
					$flag = 1;
				}
			}
			$flag = 0; 
				#year
		} 
    	$mainFlag = 0; 
	}
}
